package: staff 
version: '1.3.1'
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/staff 

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"


page:
    title: translate:staff_title
    icon: rex-icon fa-user
    perm: staff[]
    main: true
    block: system
    prio: 15

pages:
    edit: 
        title: translate:staff_title
        icon: rex-icon fa-user
        perm: staff[]
        itemattr:
            table_name: rex_staff
    edit-category: 
        title: translate:staff_category_title
        icon: rex-icon fa-folder
        perm: staff[]
        itemattr:
            table_name: rex_staff_category
    settings:
        title: translate:staff_settings
        icon: rex-icon fa-gear
        itemclass: pull-right
        perm: admin
    docs:
        title: translate:staff_docs
        subPath: README.md 
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: staff[docs]

default_config:
    editor: 'class="form-control cke5-editor" data-lang="de" data-profile="default"'
