package: staff 
version: '1.0.0-beta1'
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/staff 

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"


page:
    title: translate:staff_title
    prio: 100
    icon: rex-icon fa-person
    perm: staff[]

pages:
    staff:
        title: translate:staff_title
        prio: 100
        icon: rex-icon fa-person
        perm: staff[]
        subpages:
            edit: 
                title: translate:staff_title
                icon: rex-icon fa-person
                perm: staff[]
                subPath: pages/data_edit.php
                itemattr:
                    table_name: rex_staff
            settings:
                title: translate:staff_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:staff_docs
                subPath: README.md  # Gibt anstelle einer Seite unter `pages` die README.md des Addons aus
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: staff[docs]
