package: staff 
version: '1.0.0'
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/staff 

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"


page:
    title: translate:staff_title
    icon: rex-icon fa-person

pages:
    edit: 
        title: translate:staff_title
        block: system               
        prio: 15
        icon: rex-icon fa-person
        perm: staff[]
    settings:
        title: translate:staff_settings
        icon: rex-icon fa-gear
        itemclass: pull-right
        perm: admin
    docs:
        title: translate:staff_docs
        subPath: README.md  # Gibt anstelle einer Seite unter `pages` die README.md des Addons aus
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: staff[docs]
