package: staff 
version: '1.4.0'
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/staff 

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"


page:
    title: translate:staff_title
    icon: rex-icon fa-user
    perm: staff[]
    main: true
    block: system
    prio: 19

pages:
    person: 
        title: translate:staff_title
        icon: rex-icon fa-user
        perm: staff[]
    category: 
        title: translate:staff_category_title
        icon: rex-icon fa-folder
        perm: staff[]
    settings:
        title: translate:staff_settings
        icon: rex-icon fa-gear
        itemClass: pull-right
        perm: admin
    docs:
        title: translate:staff_docs
        icon: rex-icon fa-info-circle
        itemClass: pull-right
        perm: staff[docs]

default_config:
    editor: 'class="form-control cke5-editor" data-lang="de" data-profile="default"'
